### PR TITLE
manifest file updated. fixed options page settings

### PR DESCRIPTION
**Pull request by leninhasda**
options page doesn't seem to work on newer versions of chrome as syntax for it in manifest file has been changed. updated the manifest file & also kept the previous syntax for older version of chrome :smile:

### CODE REVIEW

**Comment by torifat** [comment]
screenshot 2015-02-04 04 09 52

**Comment by leninhasda** [comment]
i'm confused @torifat vai :confused:
wasn't it like that ? or should there be a new line at the end ?

**Comment by torifat** [comment]
Just add a new line in the end.

**Comment by leninhasda** [comment]
done. :smiley:

**Comment by torifat** [comment]
:+1:

**Pull request merged**
